# Generated by Django 6.0.1 on 2026-01-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tech',
            name='category',
            field=models.CharField(choices=[('backend', 'Backend'), ('frontend', 'Frontend'), ('database', 'Database'), ('devops', 'DevOps'), ('tools', 'Tools')], default='backend', max_length=50),
        ),
        migrations.AddField(
            model_name='tech',
            name='icon',
            field=models.CharField(blank=True, help_text='Bootstrap icon class, e.g. bi bi-database', max_length=50),
        ),
    ]
