# Generated by Django 6.0.1 on 2026-04-13 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_github_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_private_repo',
            field=models.BooleanField(default=False),
        ),
    ]
