# Generated by Django 6.0.1 on 2026-04-09 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='is_read',
            new_name='read',
        ),
    ]
