# Generated by Django 6.0.1 on 2026-04-09 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_rename_is_read_contactmessage_read'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactmessage',
            old_name='read',
            new_name='is_read',
        ),
    ]
