# Generated by Django 6.0.1 on 2026-04-03 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogtag_blogpost_tags'),
        ('projects', '0002_tech_category_tech_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='tech_stack',
            field=models.ManyToManyField(blank=True, related_name='blog_posts', to='projects.tech'),
        ),
    ]
