# Generated by Django 6.0.1 on 2026-04-03 04:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blogpost_tech_stack'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='tech_stack',
        ),
    ]
